### ISSUE TITLE
Trying to contact you regarding Repost for Android

### ISSUE THREAD

**Issue by willbailey** [jallen/AFS3Client#4]
Sorry for the random issue, please close this once you see it, but I've been trying to find a way to contact you. I'm an engineer at Instagram working on the Layout application. Repost for Android has an issue where it is incorrectly sending to Layout instead of the main Instagram app. I believe the problem is that you are querying the package manager for apps that support action send with a package name like com.instagram. Layout is com.instagram.layout, the main app is com.instagram.android. Can you check if there's a simple fix for this on your side. We could try to work around it from our side by forwarding on to the main app, but that's not ideal. I think both of our users will be happier once this is resolved.

Thanks!

**Comment by jallen** [comment]
Thanks for contacting me about this Will. 

I'll try to get the fix out ASAP. 

I added my email to my profile in case you need to get a hold of me again :)
